config/routes.rb
Rails.application.routes.draw do
root 'posts#index'
get "sign_up" => "users#new", :as => "sign_up"
get "/log-in" => "sessions#new"
post "/log-in" => "sessions#create"
get "/log-out" => "sessions#destroy", as: :log_out

resources :posts do
  resources :comments
end
resources :users
resources :sessions

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password



 def encrypt_password
   self.password_salt = BCrypt::Engine.generate_salt
   self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
 end

 def self.authenticate(email, password)
  user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable


  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(comments_params)
      if @comment.save
        redirect_to @commentable, notice: "Comment created."
      else
        render :new
      end
  end

  def destroy
  end

  


  private

  def load_commentable
    resource, id = request.path.split('/')[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end


  def comments_params
    params.require(:comment).permit(:content, :email, :name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def index
    @post = Post.all
    @posts = Post.order('created_at DESC')
    ##@posts_by_month = Post.find(:all, :order => 'created_at DESC').group_by { |post| post.created_at.strftime("%B %Y") }
  end
  

  def month_count
    @posts_by_month = Post.find(:all, :order => 'created_at DESC').group_by { |post| post.created_at.strftime("%B %Y") }
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to @post
  end

  private
  def post_params
    params.require(:post).permit(:title, :text)
  end





end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  

  def create
    @user = User.authenticate(params[:email], params[:password])
      if @user
        flash[:notice] = "You've been logged in."
        session[:user_id] = @user.id
        redirect_to root_path
     else
        flash[:alert] = "There was a problem logging you in."
        redirect_to log_in_path
     end
  end
 

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash.keep[:notice] = "Signed Up!"
      redirect_to :root    
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      render "new"
    end
  end


  def new
    @user = User.new   
  end

  def show
    @user = User.find(params[:id])
  end




private
  

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def signed_in?
    !current_user.nil?
  end


  def current_user?(user)
    user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  
end

app/views/comments/_comments.html.erb
<ul id="comments" class="comments">
    <li class="comment">
        <div class="clearfix">
            <h4 class="pull-left">John</h4>
            <p class="pull-right">9:41 PM on August 24, 2013</p>
        </div>
        <p>
            <em>I don't believe in astrology but still your writing style is really great!</em>
        </p>
    </li>
 
    <li class="comment clearfix">
        <div class="clearfix">
            <h4 class="pull-left">John</h4>
            <p class="pull-right">9:41 PM on August 24, 2013</p>
        </div>
        <p>
            <em>I don't believe in astrology but still your writing style is really great!</em>
        </p>
    </li>
</ul>

app/views/comments/_form.html.erb
<div class="well">
 
    <h4>Leave a comment</h4>
 
    <form role="form" class="clearfix">
 
        <div class="col-md-6 form-group">
            <label class="sr-only" for="name">Name</label>
            <input type="text" class="form-control" id="name" placeholder="Name">
        </div>
 
        <div class="col-md-6 form-group">
            <label class="sr-only" for="email">Email</label>
            <input type="email" class="form-control" id="email" placeholder="Email">
        </div>
 
        <div class="col-md-12 form-group">
            <label class="sr-only" for="email">Comment</label>
            <textarea class="form-control" id="comment" placeholder="Comment"></textarea>
        </div>
 
        <div class="col-md-12 form-group text-right">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
 
    </form>                   
</div>

app/views/comments/index.html.erb
<h1>Comments</h1>

<div id="comments">
<% @comments.each do |comment| %>
  <div class>
    <%= comment.content %>

  </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
       <div class="container">
        <hr />
          <p class="text-center">Copyright © Wide Open Gaming 2014. All rights reserved.</p>
        </div>
    </footer>
 

app/views/layouts/_header.html.erb
<body>
    

  
<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">         
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="index.html" class="navbar-brand">Wide Open Gaming</a>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <form class="navbar-form navbar-right" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav">
                <li class="active"><%= link_to "Home", root_path %></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Games</a></li>
                <li><a href="#">Videos</a></li>
               <% if current_user %>
                 <li><a>Logged in as <%= current_user.email %></a></li>
                 <li><%= link_to "Log out", log_out_path %></li>
               <% else %>
                 <li><%= link_to "Sign up", sign_up_path %></li>
                 <li><%= link_to "Log in", log_in_path %></li>
               <% end %>

                
            </ul>
        </nav>
    </div>
</header>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gaming</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>




 <%= render 'layouts/header' %>



<%= yield %>



<%= render 'layouts/footer' %>
</html>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8">
 
            <!-- heading -->
            <h1>Latest Posts</h1>

            
 
            <!-- list of posts -->
            <% @post.each do |post| %>
            <article>
                <h2><%= link_to post.title, post_path(post) %></h2>
 
                <div class="row">
                    <div class="group1 col-sm-6 col-md-6">
                        <span class="glyphicon glyphicon-folder-open"></span>  <a href="#">Tags</a>
                          <span class="glyphicon glyphicon-bookmark"></span> <a href="#">Aries</a>, 
                        <a href="#">Fire</a>, <a href="#">Mars</a>
                    </div>
                    <div class="group2 col-sm-6 col-md-6">
                        <span class="glyphicon glyphicon-pencil"></span> <a href="singlepost.html#comments">20 Comments</a>                             
                          <span class="glyphicon glyphicon-time"></span> <%= post.created_at %>                         
                    </div>
                </div>
 
                <hr>
 
                <img src="http://placehold.it/900x300" class="img-responsive">
 
                <br />

                <p class="lead"></p>

                <p><%= post.text %></p>
 
                
 
         
 
    
 
                <p class="text-right">
                    <%= link_to "continue reading...", post_path(post) %>
                </p>
 
                <hr>
 
            </article>
            <% end %>
          
 
            <!-- pager -->
            <ul class="pager"> 
                <li class="previous">
                    <a href="#">← Older</a>
                </li> 
                <li class="next">
                    <a href="#">Newer →</a>
                </li> 
            </ul>
        </div>
        <div class="col-md-4">
            <!-- Subscribe to my feed widget -->
    <div class="well text-center">
        <p class="lead">
            Don't want to miss updates? Please click the below button!
        </p>
        <button class="btn btn-primary btn-lg">Subscribe to my feed</button>
    </div>
    <div class="panel panel-default">
    <div class="panel-heading">
        <h4>Categories</h4>
    </div>
    <ul class="list-group">
        <li class="list-group-item"><a href="#">Signs</a></li>
        <li class="list-group-item"><a href="#">Elements</a></li>
        <li class="list-group-item"><a href="#">Planets</a></li>
        <li class="list-group-item"><a href="#">Cusps</a></li>
        <li class="list-group-item"><a href="#">Compatibility</a></li>
    </ul>
</div>
 
 
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Recent Comments</h4>
    </div>
    <ul class="list-group">
        <li class="list-group-item"><a href="#">I don't believe in astrology but still your writing style is really great! - <em>john</em></a></li>
        <li class="list-group-item"><a href="#">Wow.. what you said is really true! I'm an aries though - <em>Anto</em></a></li>
        <li class="list-group-item"><a href="#">Does capricorn and aries is compatibile? - <em>Sarah</em></a></li>
        <li class="list-group-item"><a href="#">I'm a cancer woman been in love with Leo. Will this work? - <em>Mary</em></a></li>
    </ul>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Tags</h4>
    </div>
    <div class="panel-body">
        <ul class="list-inline">
            <li><a href="#">Aries</a></li>
            <li><a href="#">Fire</a></li>
            <li><a href="#">Mars</a></li>
            <li><a href="#">Taurus</a></li>
            <li><a href="#">Earth</a></li>
            <li><a href="#">Moon</a></li>
            <li><a href="#">Gemini</a></li>
            <li><a href="#">Air</a></li>
            <li><a href="#">Mercury</a></li>
            <li><a href="#">Cancer</a></li>
        </ul>
    </div>
</div>
 
    <!-- Other widgets -->
        </div>
    </div>
</div

app/views/posts/new.html.erb
<%= form_for @post do |f| %>

   <div class = "form-horizontal">

      <div class="form-group">
                   <%= f.label :title, class: "col-sm-2 control-label" %>
             <div class="col-sm-6">
                   <%= f.text_field :title, class: "form-control", autofocus: true %>
             </div>  
      </div>

      
      
           <div class="form-group">
                   <%= f.label :text, class: "col-sm-2 control-label" %>
             <div class="col-sm-6">
                   <%= f.text_area :text, class: "form-control" %>
             </div>  
           </div>
       
           
          <div class="form-group">
                <div class="col-sm-offset-2 col-sm-6">
                      <%= f.submit "Create Post", class: "btn btn-primary" %>
               </div>
          </div>

  </div>



<% end %>

app/views/posts/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8">
 
            <!-- heading -->
            <h1>Latest Posts</h1>

            
 
            <!-- list of posts -->
            
            <article>
                <h2><%= @post.title %></h2>
 
                <div class="row">
                    <div class="group1 col-sm-6 col-md-6">
                        <span class="glyphicon glyphicon-folder-open"></span>  <a href="#">Tags</a>
                          <span class="glyphicon glyphicon-bookmark"></span> <a href="#">Aries</a>, 
                        <a href="#">Fire</a>, <a href="#">Mars</a>
                    </div>
                    <div class="group2 col-sm-6 col-md-6">
                        <span class="glyphicon glyphicon-pencil"></span> <a href="singlepost.html#comments">20 Comments</a>                             
                          <span class="glyphicon glyphicon-time"></span> <%=@post.created_at %>                         
                    </div>
                </div>
 
                <hr>
 
                <img src="http://placehold.it/900x300" class="img-responsive">
 
                <br />

                <p class="lead"></p>

                <p><%= @post.text %></p>
 
                
 
         
 
    
 
                <p class="text-right">
                   
                </p>
 
                <hr>
 
            </article>
        
          
 
            <!-- pager -->
            <ul class="pager"> 
                <li class="previous">
                    <a href="#">← Back to posts</a>
                </li>  
            </ul>
       <%= render 'comments/form' %>
       <%= render 'comments/comments' %>
        </div>


        <div class="col-md-4">
            <!-- Subscribe to my feed widget -->
    <div class="well text-center">
        <p class="lead">
            Don't want to miss updates? Please click the below button!
        </p>
        <button class="btn btn-primary btn-lg">Subscribe to my feed</button>
    </div>
    <div class="panel panel-default">
    <div class="panel-heading">
        <h4>Categories</h4>
    </div>
    <ul class="list-group">
        <li class="list-group-item"><a href="#">Signs</a></li>
        <li class="list-group-item"><a href="#">Elements</a></li>
        <li class="list-group-item"><a href="#">Planets</a></li>
        <li class="list-group-item"><a href="#">Cusps</a></li>
        <li class="list-group-item"><a href="#">Compatibility</a></li>
    </ul>
</div>
 
 
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Recent Comments</h4>
    </div>
    <ul class="list-group">
        <li class="list-group-item"><a href="#">I don't believe in astrology but still your writing style is really great! - <em>john</em></a></li>
        <li class="list-group-item"><a href="#">Wow.. what you said is really true! I'm an aries though - <em>Anto</em></a></li>
        <li class="list-group-item"><a href="#">Does capricorn and aries is compatibile? - <em>Sarah</em></a></li>
        <li class="list-group-item"><a href="#">I'm a cancer woman been in love with Leo. Will this work? - <em>Mary</em></a></li>
    </ul>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Tags</h4>
    </div>
    <div class="panel-body">
        <ul class="list-inline">
            <li><a href="#">Aries</a></li>
            <li><a href="#">Fire</a></li>
            <li><a href="#">Mars</a></li>
            <li><a href="#">Taurus</a></li>
            <li><a href="#">Earth</a></li>
            <li><a href="#">Moon</a></li>
            <li><a href="#">Gemini</a></li>
            <li><a href="#">Air</a></li>
            <li><a href="#">Mercury</a></li>
            <li><a href="#">Cancer</a></li>
        </ul>
    </div>
</div>
 
    <!-- Other widgets -->
        </div>
    </div>
</div

app/views/users/new.html.erb
 <div class = "container">    
   <center>
        <h3 class = "user-sign-up">Sign Up</h3>
     </center>
     <br>
     
    <%= form_for User.new do |f| %>

  <div class = "form-horizontal">
    <div class="form-group">
        <%= f.label :email, class: "col-sm-2 control-label" %>
        <div class="col-sm-6">
        <%= f.email_field :email, class: "form-control" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :password, class: "col-sm-2 control-label" %>
        <div class="col-sm-6">
        <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
        <div class="col-sm-6">
        <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
        </div>
    </div>

    <div class="form-group">
                <div class="col-sm-offset-2 col-sm-6">
                      <%= f.submit "Sign Up", class: "btn btn-primary" %>
               </div>


  </div>

</div>  
    <% end %>